### ISSUE TITLE
Reinstating the ParaView builds for Windows

### ISSUE THREAD

**Issue by tinyendian** [conda-forge/paraview-feedstock#144]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Hi, I am developing a plugin for ParaView that I recently made available via conda-forge (https://anaconda.org/conda-forge/lfric_reader), and I am thus benefiting heavily from your hard work with maintaining the ParaView package (thanks!!).

A few weeks ago, I added a Windows version and noticed that ParaView for Windows is not currently maintained in the feedstock, presumably due to Windows cloud builds exceeding the 6 hour build time limit (#102).

So I was wondering if you have tried using parallel builds via Ninja build on Windows? The current build setup with NMake only runs on a single core. I tried building ParaView using `conda build` and the recipe from the `paraview-feedstock` repository on two cores on my mid-range Windows laptop, which completed in just under 3h. It could be that the cloud builds run on two logical/SMT cores and/or may generally be slower than my laptop, but there is a good chance that a parallel build could bring build times down enough to fit within the limit.

If you are interested, I could create a pull request for this. Also happy to contribute to maintaining the Windows builds going forward, if you like.

**Comment by jschueller** [comment]
go ahead
