### ISSUE TITLE
No Python 3.7 version

### ISSUE THREAD

**Issue by jmozmoz** [conda-forge/paraview-feedstock#17]
Issue: There is no Python 3.7 version of this package at conda-forge

Are there any plans to add a Python 3.7 version of the package soon? Or is this an upstream problem? According to this bug report https://gitlab.kitware.com/paraview/paraview/issues/18323 paraview should compile with Python 3.7

**Comment by jschueller** [comment]
this will take some time: https://github.com/conda-forge/conda-forge.github.io/issues/649
