### ISSUE TITLE
Build with osmesa 

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [conda-forge/paraview-feedstock#223]
### Comment:

Hi!

I would like to [run paraview in GitHub actions](https://github.com/RemDelaporteMathurin/FESTIM-review/blob/7132df837c144c9b4eed844e8c5b56ec0aeecc30/.github/workflows/run_cases.yml#L68-L87).
I realised [I need either the OSmesa or the EGL build of Paraview](https://discourse.paraview.org/t/run-paraview-in-github-actions/13101)

I wondered if there was such a build distributed with Conda?

Thanks!

**Comment by jschueller** [comment]
yes there is an egl variant

**Comment by RemDelaporteMathurin** [comment]
> yes there is an egl variant

Awesome! Do you have any pointers or links for this variant?

**Comment by jschueller** [comment]
see the files with the _egl suffix instead of _qt:
https://anaconda.org/conda-forge/paraview/files
