### ISSUE TITLE
missing MEDReader plugin

### ISSUE THREAD

**Issue by bahugo** [conda-forge/paraview-feedstock#241]
### Comment:

Hello,
I just discovered that paraview last version 5.12 is now available in conda-forge thanks to your work.
But I'm still missing paraview the official plugins.
I'd love to use this conda package but I can't because I need MEDReader plugin.
Would it be possible to add those plugins in the current package or maybe another one?
Best regards

**Comment by jschueller** [comment]
it seems this plugin is built from paravis sources so I guess that will be another package
you can open a package request at conda-forge/staged-recipes if someone wants to pick it up
