### ISSUE TITLE
EGL-based Variant Build

### ISSUE THREAD

**Issue by NickLeaf** [conda-forge/paraview-feedstock#54]
Issue: Add an EGL-based build variant to allow GPU-accelerated rendering in headless environments.

It would also be good to enable some other features in the build, such as the ray tracing back ends (NVIDIA VisRTX and Intel OSPRay) and a broader set of plugins (e.g. NVIDIA IndeX).

Suggested CMake variables:
<details>

```
-DVTK_USE_X=OFF \
-DVTK_OPENGL_HAS_EGL=ON \
-DPARAVIEW_PLUGIN_ENABLE_pvNVIDIAIndeX=ON \
-DVTK_ENABLE_VISRTX=ON \
-DVTK_ENABLE_OSPRAY=ON \
```
</details>

Tagging @jakirkham for visibility.

**Comment by jakirkham** [comment]
Thanks for raising and cc-ing me @NickLeaf! 😄

How does this compare to what is being done in VTK currently? In particular they are using [OSMesa in one of their builds]( https://github.com/conda-forge/vtk-feedstock/blob/4d298786df9f5690078c2350814ae74a90a3849b/recipe/build.sh#L21-L28 ). Would that be useful for this effort or is this that orthogonal?

**Comment by NickLeaf** [comment]
OSMesa only supports the Nouveau driver with software rendering as a fallback, I believe.

**Comment by jakirkham** [comment]
Are there extra dependencies that would be needed for this build to work? Also what happens if a package with these flags is installed on a system without these requirements met? Is ParaView smart enough to detect that at runtime or should there be a different build of the package for this case?

**Comment by NickLeaf** [comment]
The EGL libraries are typically distributed with the driver. I believe Mesa also has an implementation, so I think we would just have to make sure that ParaView picked up the driver library if available, and only picked up the mesa version if not. I think it's be reasonable to have a specific version of the package for EGL, though.

**Comment by banesullivan** [comment]
+1 for this - anyone have traction on this?

**Comment by nantille** [comment]
+1 – is it complicated to implement the suggestion of @NickLeaf ?

**Comment by Jeff0821** [comment]
Hi @jakirkham ,
any update about this issue?

**Comment by jakirkham** [comment]
AFAIK no one is working on this issue. Please feel free to pick it up if it is of interest to you 🙂

**Comment by Jeff0821** [comment]
Thank you @jakirkham  for your information.
Since now there are many machines in HPC cluster have GPUs, EGL version is very important.
I am very new to this area, I will learn some basis and have a try later on.

**Comment by basnijholt** [comment]
I am making an attempt to solve this issue in https://github.com/conda-forge/paraview-feedstock/pull/126/.

Feedback is appreciated :)
