### ISSUE TITLE
Missing paraview binary in the Conda paraview package

### ISSUE THREAD

**Issue by bokertov** [conda-forge/paraview-feedstock#6]
I installed paraview in Miniconda on my linux desktop:
https://anaconda.org/conda-forge/paraview

However, there is only paraview-config under ~/miniconda3/bin/, and no binary "paraview".

Is this a bug?

**Comment by jschueller** [comment]
not a bug: the gui is disabled

**Comment by pgunn** [comment]
This is a very surprising packaging for paraview, disabling the way most people (I expect) would expect to use the package. It'd be great if the design decisions that led to this could be reconsidered.

**Comment by bgruening** [comment]
@pgunn I assume a PR is welcome to enable the GUI.

**Comment by michaelkarlcoleman** [comment]
Just ran into this myself, and also curious what's up.  Is the GUI really hard to build?  Or is there something else that makes it bad to try?

**Comment by jschueller** [comment]
I dont recall why, but it doesnt hurt to try https://github.com/conda-forge/paraview-feedstock/pull/46

**Comment by jschueller** [comment]
@michaelkarlcoleman @bokertov @pgunn can you retry ? once the new binaries are published ?

**Comment by michaelkarlcoleman** [comment]
@jschueller It seems like the new package works.  

(I say "seems like", as it won't actually display for me due to "too old OpenGL", but I don't believe that's an issue with the package.)

Thanks!
